// src/components/Navigation.tsx
import classNames from 'classnames';
import Link from 'next/link';
import React, { useState } from 'react';
import navigation from '../data/navigation.json';

function Navigation() {

  const [isNavOpen, setIsNavOpen] = useState(false);

  return (
    <nav className={classNames(
      'site-header-nav',
      { 'site-header-nav-open': isNavOpen }
    )}>
      <button className="site-header-nav-toggle" aria-label="Menu" onClick={() => setIsNavOpen(!isNavOpen)}>
        <img src="/icons/nav-toggle.svg" alt="Toggle Navigation" />
      </button>
      <ul className="site-header-nav-list">
        {navigation.map((navigationLink) => {
          return (
            <li key={navigationLink.url}>
              <Link href={navigationLink.url}>
                {navigationLink.title}
              </Link>
            </li>
          );
        })}
      </ul>
    </nav>
  );
}
export default Navigation;

// src/routes/Navigation.svelte
<script lang="ts">
  import { page } from '$app/stores';
  import navigation from '../data/navigation.json';

  let isNavOpen = false;

  function toggleNav() {
    isNavOpen = !isNavOpen;
  }
  function closeNav() {
    isNavOpen = false;
  }
  // Normalize the given URL pathname (e.g. /about/me -> about/me)
  function normalizePathname(pathname: string) {
    return pathname.replace(/(^\/)|(\/$)/gi, '');
  }
  function isCurrentPage(navigationLink: typeof navigation[number], $currentPage: typeof $page) {
    return normalizePathname(navigationLink.url) === normalizePathname($currentPage.url.pathname);
  }
</script>

<nav class="site-header-nav" class:site-header-nav-open={isNavOpen}>
  <button class="site-header-nav-toggle" aria-label="Menu" on:click={toggleNav}>
    <img src="/icons/nav-toggle.svg" alt="Toggle Navigation" />
  </button>
  <ul class="site-header-nav-list">
    {#each navigation as navigationLink (navigationLink.url)}
      <li class:is-current-page={isCurrentPage(navigationLink, $page)}>
        <a href={navigationLink.url} on:click={closeNav}>
          {navigationLink.title}
        </a>
      </li>
    {/each}
  </ul>
</nav>
