// src/routes/contact/ContactLink.svelte
<script lang="ts">
  import type { ContactLinkEntry } from '../types';
  export let contactLink: ContactLinkEntry;
  export let isCompact = false;
</script>

<article
  data-entry-id={contactLink.id}
  class="entry contact-link"
  class:entry-compact={isCompact}
  class:contact-link-compact={isCompact}
>
  {#if !isCompact}
    <a
      class="entry-image contact-link-image"
      href={contactLink.direct_url}
      aria-labelledby={`contact-link-${contactLink.id}`}
    >
      <img src={`/icons/contact-links/${contactLink.id}.svg`} alt="" width={64} height={64} />
    </a>
    <div class="entry-main contact-link-main">
      <h3 class="entry-title contact-link-title">
        <a href={contactLink.direct_url} id={`contact-link-${contactLink.id}`}>
          {contactLink.title}
        </a>
      </h3>

      <div class="entry-desc contact-link-desc">
        {contactLink.description}
      </div>
    </div>
  {:else}
    <a
      class="entry-image contact-link-image"
      href={contactLink.direct_url}
      title={contactLink.title}
    >
      <img
        src={`/icons/contact-links/${contactLink.id}.svg`}
        alt={contactLink.title}
        width={40}
        height={40}
      />
    </a>
  {/if}
</article>

// src/components/ContactLink.tsx
import classNames from 'classnames';
import Image from 'next/image';
import { ContactLinkEntry } from './types';

type Props = { contactLink: ContactLinkEntry; isCompact?: boolean };

function ContactLink({ contactLink, isCompact = false }: Props) {
  return (
    <article
      data-entry-id={contactLink.id}
      className={classNames(
        'entry',
        'contact-link',
        { 'entry-compact': isCompact },
        { 'contact-link-compact': isCompact }
      )}
    >
      {!isCompact ? (
        <>
          <a
            className="entry-image contact-link-image"
            href={contactLink.direct_url}
            aria-labelledby={`contact-link-${contactLink.id}`}
          >
            <Image
              src={`/icons/contact-links/${contactLink.id}.svg`}
              alt=""
              width={64}
              height={64}
              priority={true}
            />
          </a>

          <div className="entry-main contact-link-main">
            <h3 className="entry-title contact-link-title">
              <a
                href={contactLink.direct_url}
                id={`contact-link-${contactLink.id}`}
              >
                {contactLink.title}
              </a>
            </h3>

            <div className="entry-desc contact-link-desc">
              {contactLink.description}
            </div>
          </div>
        </>
      ) : (
        <>
          <a
            className="entry-image contact-link-image"
            href={contactLink.direct_url}
            aria-label={contactLink.title}
            title={contactLink.title}
          >
            <Image
              src={`/icons/contact-links/${contactLink.id}.svg`}
              alt=""
              width={40}
              height={40}
            />
          </a>
        </>
      )}
    </article>
  );
}
export default ContactLink;
