// src/routes/contact/ContactLinks.svelte
<script lang="ts">
  import { page } from '$app/stores';
  import { keyBy } from 'lodash-es';
  import contactLinkMetadata from '../../data/contact-links.json';
  import type { ContactLinkMap } from '../types';
  import ContactLink from './ContactLink.svelte';

  const { contactLinks } = $page.data;
  export let isCompact = false;

  const contactLinksByName: ContactLinkMap = keyBy(contactLinks, 'id');
</script>

<div class="entry-list contact-link-list" class:entry-list-compact={isCompact}>
  {#each contactLinkMetadata.contactLinks as contactLinkName (contactLinkName)}
    {#if contactLinksByName[contactLinkName]}
      <ContactLink contactLink={contactLinksByName[contactLinkName]} {isCompact} />
    {/if}
  {/each}
</div>

// src/components/ContactLinks.tsx
import classNames from 'classnames';
import { keyBy } from 'lodash-es';
import React from 'react';
import contactLinkMetadata from '../data/contact-links.json';
import ContactLink from './ContactLink';
import { ContactLinkEntry, ContactLinkMap } from './types';

type Props = { contactLinks: ContactLinkEntry[], isCompact?: boolean };

function ContactLinks({ contactLinks, isCompact = false }: Props) {

  const contactLinksByName: ContactLinkMap = keyBy(contactLinks, 'id');

  return (
    <div className={classNames(
      'entry-list',
      'contact-link-list',
      { 'entry-list-compact': isCompact },
      { 'contact-link-list-compact': isCompact }
    )}>
      {contactLinkMetadata.contactLinks.map((contactLinkName) => {
        const contactLink = contactLinksByName[contactLinkName];
        return (
          <ContactLink
            key={contactLink.id}
            contactLink={contactLink}
            isCompact={isCompact} />
        );
      })}
    </div>
  );
}
export default ContactLinks;
