// src/routes/ContactLinks.svelte
<script lang="ts">
  import { page } from '$app/stores';
  import { keyBy } from 'lodash-es';
  import contactLinkMetadata from '../data/contact-links.json';
  import type { PageData } from './$types';
  import { analyticsEntryListeners } from './analyticsEntryListeners';
  import ContactLink from './ContactLink.svelte';
  import type { ContactLinkMap } from './types';

  const { contactLinks } = $page.data as PageData;
  export let isCompact: boolean = false;

  const contactLinksByName: ContactLinkMap = keyBy(contactLinks, 'id');
</script>

<div
  class="entry-list contact-link-list"
  class:entry-list-compact={isCompact}
  class:contact-link-list-compact={isCompact}
  use:analyticsEntryListeners={'contact links'}
>
  {#each contactLinkMetadata.contactLinks as contactLinkName}
    <ContactLink contactLink={contactLinksByName[contactLinkName]} {isCompact} />
  {/each}
</div>

// src/components/ContactLinks.tsx
import classNames from 'classnames';
import { keyBy } from 'lodash-es';
import React from 'react';
import contactLinkMetadata from '../data/contact-links.json';
import ContactLink from './ContactLink';
import { ContactLinkEntry, ContactLinkMap } from './types';

type Props = { contactLinks: ContactLinkEntry[], isCompact?: boolean };

function ContactLinks({ contactLinks, isCompact = false }: Props) {

  const contactLinksByName: ContactLinkMap = keyBy(contactLinks, 'id');

  return (
    <div className={classNames(
      'entry-list',
      'contact-link-list',
      { 'entry-list-compact': isCompact },
      { 'contact-link-list-compact': isCompact }
    )}>
      {contactLinkMetadata.contactLinks.map((contactLinkName) => {
        const contactLink = contactLinksByName[contactLinkName];
        return (
          <ContactLink
            key={contactLink.id}
            contactLink={contactLink}
            isCompact={isCompact} />
        );
      })}
    </div>
  );
}
export default ContactLinks;
