// src/routes/Head.svelte
<script lang="ts">
  import { page } from '$app/stores';
  import site from '$data/site.json';
  import portrait120 from '$images/self-portrait-v6.jpg?w=120&imagetools';
  import portrait152 from '$images/self-portrait-v6.jpg?w=152&imagetools';
  import portrait180 from '$images/self-portrait-v6.jpg?w=180&imagetools';
  import portrait192 from '$images/self-portrait-v6.jpg?w=192&imagetools';
  import portrait32 from '$images/self-portrait-v6.jpg?w=32&imagetools';
  import portrait76 from '$images/self-portrait-v6.jpg?w=76&imagetools';
  import JsonLd from '$routes/JsonLd.svelte';

  let isHomepage: boolean;
  let pageSeoTitle: string;
  let pageSeoUrl: string;
  let pageSeoDescription: string;
  let pageSeoImage = `${site.url}/images/social-preview.png`;

  // SvelteKit does not seem to like if..else blocks within <svelte:head>; if we
  // try to conditionally set the <title> within <svelte:head> itself, then the
  // page title stops updating after the first or second page navigate; to fix
  // this, we move the conditional logic to the TypeScript section of the layout
  // component, and use a reactive statement to update the page title whenever
  // the value of 'page' changes
  let renderedTitle: string;
  $: {
    isHomepage = $page.data.id === 'home';
    if (isHomepage) {
      renderedTitle = `${site.title} | ${site.tagline}`;
      pageSeoTitle = `${site.title} | ${site.tagline}`;
      pageSeoDescription = site.description;
    } else {
      renderedTitle = `${$page.data.title} | ${site.title}`;
      pageSeoTitle = $page.data.title;
      pageSeoDescription = $page.data.description;
    }
    pageSeoUrl = site.url + $page.url.pathname;
  }
</script>

<svelte:head>
  <title>{renderedTitle}</title>
  <link rel="shortcut icon" href={portrait32} />
  <link rel="icon" href={portrait192} sizes="192x192" />
  <meta name="description" content={site.description} />

  <meta name="og:title" content={pageSeoTitle} />
  <meta name="og:site_title" content={site.title} />
  <meta name="og:description" content={site.description} />
  <meta name="og:url" content={pageSeoUrl} />
  <meta name="og:image" content={pageSeoImage} />
  <meta name="og:type" content="website" />
  <meta name="twitter:card" content="summary_large_image" />
  <meta name="twitter:site" content={site.twitterUsername} />
  <meta name="twitter:creator" content={site.twitterUsername} />
  <meta name="twitter:title" content={pageSeoTitle} />
  <meta name="twitter:description" content={site.description} />
  <meta name="twitter:image" content={pageSeoImage} />
  <meta name="google-site-verification" content={site.googleSiteVerification} />
  <link rel="canonical" href={pageSeoUrl} />
  <link rel="alternate" hrefLang="en-US" href={pageSeoUrl} />
  <JsonLd
    title={pageSeoTitle}
    description={pageSeoDescription}
    url={pageSeoUrl}
    type={isHomepage ? 'WebSite' : 'WebPage'}
  />
  <link rel="apple-touch-icon" href={portrait76} sizes="76x76" />
  <link rel="apple-touch-icon" href={portrait120} sizes="120x120" />
  <link rel="apple-touch-icon" href={portrait152} sizes="152x152" />
  <link rel="apple-touch-icon" href={portrait180} sizes="180x180" />
  <title>{renderedTitle}</title>
  <meta name="description" content={$page.data.description} />
</svelte:head>

// src/components/Head.tsx
import { graphql, useStaticQuery } from 'gatsby';
import React from 'react';
import { Helmet } from 'react-helmet';
import { HeadQuery } from '../../graphql-types';
import { getGravatarUrl } from '../utilities/gravatar';

type Props = { pageTitle: string, pageSlug: string };

function Head({ pageTitle, pageSlug }: Props) {

  const queryResults: HeadQuery = useStaticQuery(query);
  const {
    siteUrl,
    siteTitle,
    siteTagline,
    siteDescription,
    siteEmail,
    twitterUsername,
    googleSiteVerification
  } = queryResults.site.siteMetadata;
  const { allGoogleFontCss } = queryResults;
  const isHomepage = pageSlug === '/';
  const pageSeoTitle = (isHomepage ? `${siteTitle} | ${siteTagline}` : pageTitle);
  const pageSeoUrl = siteUrl + pageSlug;
  const pageSeoImage = `${siteUrl}/images/social-preview.png`;

  const renderedTitle = isHomepage ?
    `${siteTitle} | ${siteTagline}` :
    `${pageTitle} | ${siteTitle}`;

  const appleTouchIcons = [76, 120, 152, 180].map((size) => {
    return { size, url: getGravatarUrl(siteEmail, size) };
  });

  const jsonLd = {
    description: siteDescription,
    headline: isHomepage ? siteTitle : pageTitle,
    url: pageSeoUrl,
    '@type': isHomepage ? 'WebSite' : 'WebPage',
    name: isHomepage ? siteTitle : pageTitle,
    '@context': 'https://schema.org'
  };

  return (
    <Helmet
      htmlAttributes={{ lang: 'en-US' }}
      bodyAttributes={{ 'data-page-slug': pageSlug }}
      title={renderedTitle}>
      <link rel="shortcut icon" href={getGravatarUrl(siteEmail, 32)} />
      <link rel="icon" href={getGravatarUrl(siteEmail, 192)} sizes="192x192" />

      <meta name="og:title" content={pageSeoTitle} />
      <meta name="og:site_title" content={siteTitle} />
      <meta name="og:description" content={siteDescription} />
      <meta name="og:url" content={pageSeoUrl} />
      <meta name="og:image" content={pageSeoImage} />
      <meta name="og:type" content="website" />
      <meta name="twitter:card" content="summary_large_image" />
      <meta name="twitter:site" content={twitterUsername} />
      <meta name="twitter:creator" content={twitterUsername} />
      <meta name="twitter:title" content={pageSeoTitle} />
      <meta name="twitter:description" content={siteDescription} />
      <meta name="twitter:image" content={pageSeoImage} />
      <meta name="google-site-verification" content={googleSiteVerification} />
      <link rel="canonical" href={pageSeoUrl} />
      <link rel="alternate" hrefLang="en-US" href={pageSeoUrl} />
      <script type="application/ld+json">{`${JSON.stringify(jsonLd)}`}</script>
      {appleTouchIcons.map(({ url, size }) => {
        return <link
          key={url}
          rel="apple-touch-icon"
          href={url}
          sizes={`${size}x${size}`} />;
      })}
      {allGoogleFontCss.nodes.map(({ url, css }) => {
        return css ?
          <style key={url} data-href={url} data-keep-inline>{css}</style> :
          <link key={url} rel="stylesheet" href={url} />;
      })}
    </Helmet>
  );

}
export default Head;

export const query = graphql`
  query Head {
    site {
      siteMetadata {
        siteUrl
        siteEmail
        siteTitle
        siteTagline
        siteDescription
        twitterUsername
        googleSiteVerification
      }
    }
    allGoogleFontCss {
      nodes {
        url
        css
      }
    }
  }
`;
