// src/routes/projects/Project.svelte
<script lang="ts">
	import type { PageData } from './$types';
	export let project: PageData['projects'][number];
	export let isCompact: boolean = false;
</script>

<article
	data-entry-id={project.id}
	class="entry project"
	class:entry-compact={isCompact}
	class:project-compact={isCompact}
>
	<a
		class="entry-image project-image"
		href={project.direct_url}
		aria-labelledby={`project-title-${project.id}`}
	>
		<img src={`/icons/projects/${project.id}.svg`} alt="" width={80} height={80} loading="lazy" />
	</a>

	<div class="entry-main project-main">
		<h4 class="entry-title project-title" id={`project-title-${project.id}`}>
			<a href={project.direct_url}>{project.title}</a>
		</h4>

		{#if project.description}
			{#if !isCompact}
				<p class="entry-desc project-desc">{project.description}</p>
			{/if}
		{/if}
	</div>
</article>

// src/components/Project.tsx
import classNames from 'classnames';
import Image from 'next/future/image';
import { ProjectEntry } from './types';

type Props = { project: ProjectEntry; isCompact?: boolean };

function Project({ project, isCompact = false }: Props) {
  return (
    <article
      data-entry-id={project.id}
      className={classNames(
        'entry',
        'project',
        { 'entry-compact': isCompact },
        { 'project-compact': isCompact }
      )}
    >
      <a
        className="entry-image project-image"
        href={project.direct_url}
        aria-labelledby={`project-title-${project.id}`}
      >
        <Image
          src={`/icons/projects/${project.id}.svg`}
          alt=""
          width={80}
          height={80}
        />
      </a>

      <div className="entry-main project-main">
        <h4
          className="entry-title project-title"
          id={`project-title-${project.id}`}
        >
          <a href={project.direct_url}>{project.title}</a>
        </h4>

        {project.description && !isCompact ? (
          <p className="entry-desc project-desc">{project.description}</p>
        ) : null}
      </div>
    </article>
  );
}
export default Project;
